In [1]:
import numpy as np

In [3]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[0]    #first element at index position 0

1

In [5]:
a[1]    #second element

2

In [6]:
a[-1]   #last element

10

In [7]:
list(enumerate(a))   #list of index, value tuples

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, 8),
 (8, 9),
 (9, 10)]

In [8]:
a[2:6]  #slicing from indec position 2 (incl.) till position 6 (excl.)

array([3, 4, 5, 6])

In [9]:
a[:] 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a[:5]     #all elements until index position 5 (excl.)

array([1, 2, 3, 4, 5])

In [11]:
a[6:]

array([ 7,  8,  9, 10])

In [12]:
a[::2]   #every 2nd element starting from 1st element

array([1, 3, 5, 7, 9])

In [13]:
a[2::3]  #every 3rd element starting from 3rd element (index position 2)

array([3, 6, 9])

In [14]:
a[0]=100 #ndarrays are mutable, change first element to 100
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [15]:
a[2:5]=[50,51,52]          #assigning multiple new values to multiple elements
a

array([100,   2,  50,  51,  52,   6,   7,   8,   9,  10])

In [16]:
a=np.arange(1,11)          #creating new ndarray
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
b=a[2:8]                   #making a slice of ndarray a and assign new variable b
b
#try b=a[2:8].copy() afterwards

array([3, 4, 5, 6, 7, 8])

In [20]:
b[0]=100
b

array([100,   4,   5,   6,   7,   8])

In [21]:
a

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [24]:
I=list(range(1,11))
I

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
m=I[2:8]
m

[3, 4, 5, 6, 7, 8]

In [27]:
m[0]=100
m

[100, 4, 5, 6, 7, 8]

In [28]:
I                     #no effect on I

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]