In [2]:
import numpy as np

In [4]:
#create new ndarray from 1 to 10

np.arange(1,11)                                     #arange() is one of the array creation routines based on numerical ranges

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#create new ndarray from 1 to 10 picking alternate numbers

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [7]:
#Multiplication is not an element wise operation

I=[1,2,3,4]
I*4


[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
I1=[]
I=[1,2,3,4]

for i in I:
    I1.append(i*2)
    
I1

[2, 4, 6, 8]

In [8]:
#create nadarray from 1 to 5 and then multiply

import numpy as np

a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [13]:
#element-wise (vectorized) operations are pretty simple with ndarrays

print(a*2)
print(a+2)
print(a-2)
print(a/2)
print(a//2)
print(a**18)



[2 4 6 8]
[3 4 5 6]
[-1  0  1  2]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[        1    262144 387420489         0]


In [14]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [15]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [18]:
a.sum()             #sum of all elements (ndarray method)

10

In [19]:
np.sum(a)           #sum of all elements

10

In [20]:
sum(a)

10

In [21]:
a.size              #no. of elements in ndarray (ndarray attribute)

4

In [23]:
len(a)

4

In [25]:
b=np.array([-2.4,-5.7,-3,2,1,0,5,-4.5,-6.8,6.8])
b

array([-2.4, -5.7, -3. ,  2. ,  1. ,  0. ,  5. , -4.5, -6.8,  6.8])

In [26]:
np.abs(b)           #absolute value of all elements

array([2.4, 5.7, 3. , 2. , 1. , 0. , 5. , 4.5, 6.8, 6.8])

In [27]:
np.ceil(b)         #element-wise rounding up

array([-2., -5., -3.,  2.,  1.,  0.,  5., -4., -6.,  7.])

In [28]:
np.floor(b)        #element-wise rounding down

array([-3., -6., -3.,  2.,  1.,  0.,  5., -5., -7.,  6.])